sudo: required

language: node_js

node_js:
  - "16"

# keep the npm cache around to speed up installs  
cache:
  directories:
    - node_modules
    - "$HOME/.npm"

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=licence
      script: npm run licence-check
    - env:
        - job=build
      script:
        - export NODE_OPTIONS=--max_old_space_size=8192;
        - npm ci
        - npm run build
    - env:
        - job=test
      script: npm run test
